import Link from "next/link";
import './globals.css'

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <nav style={{ padding: '10px', background: '#f4f4f4', marginBottom: '20px' }}>
          <ul style={{ display: 'flex', gap: '15px', listStyle: 'none', padding: 0 }}>
            <li>
              <Link href="/pokemon">Baza Pokémonów</Link>
            </li>
            <li>
              <Link href="/favorites">Ulubione</Link>
            </li>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}
